# fly.toml app configuration file generated for atrium on 2026-02-15T19:55:31-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atrium'
primary_region = 'sjc'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://fetauevrmimlaeketinr.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZldGF1ZXZybWltbGFla2V0aW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMDIxMzIsImV4cCI6MjA4NjY3ODEzMn0.1184MIm_l62YUHPsqoW4cTieLf_i2fB6j1o7MU1hCY8"
    NEXT_PUBLIC_APP_URL = "https://atrium.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-2x'
